package yourcaryourway.com.example.yourcaryourway.models;

import lombok.*;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.*;

@Entity
@Table(name = "client")
@Data
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = { "id" })
@Builder
@AllArgsConstructor
@ToString
public class Client {
    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}
