package yourcaryourway.com.example.yourcaryourway.models;

import lombok.*;

import java.time.LocalDateTime;

import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Size;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "user")
@Data
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = { "id" })
@Builder
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor
@ToString
public class User {
    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User email, which is login for authentication */
    @NonNull
    @Size(max = 50)
    @Email
    private String email;

    /** Encrypted password */
    @NonNull
    @Size(max = 120)
    private String password;

    /** User firstName */
    @NonNull
    @Size(max = 20)
    @Column(name = "first_name")
    private String firstName;

    /** User lastName */
    @NonNull
    @Size(max = 20)
    @Column(name = "last_name")
    private String lastName;

    /** Timestamp of creation, set once and not updatable. */
    @CreatedDate
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Initializes `createdAt` and `updatedAt` before persisting */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = this.createdAt;
    }
}
